apiVersion: v1
kind: Service
metadata:
  name: load-service
spec:
  selector:
    app: pictochat
  ports:
    - port: 80
      targetPort: 80
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  externalIPs: 
    - "192.168.7.62"